/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSkillRouteImport } from './routes/_public/skill'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicHowToIntegrateRouteImport } from './routes/_public/how-to-integrate'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicAccountIdRouteImport } from './routes/_public/$accountId'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/_dashboard'
import { Route as AdminDashboardRouteImport } from './routes/_admin/_dashboard'
import { Route as PublicFeedIndexRouteImport } from './routes/_public/feed/index'
import { Route as PublicAccountIdIndexRouteImport } from './routes/_public/$accountId/index'
import { Route as PublicFeedRoundIdRouteImport } from './routes/_public/feed/$roundId'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/_dashboard/settings'
import { Route as AuthenticatedDashboardOrgsRouteImport } from './routes/_authenticated/_dashboard/orgs'
import { Route as AuthenticatedDashboardDashboardRouteImport } from './routes/_authenticated/_dashboard/dashboard'
import { Route as AdminDashboardAdminRouteImport } from './routes/_admin/_dashboard/admin'
import { Route as AuthenticatedDashboardSettingsIndexRouteImport } from './routes/_authenticated/_dashboard/settings/index'
import { Route as AuthenticatedDashboardOrgsIndexRouteImport } from './routes/_authenticated/_dashboard/orgs/index'
import { Route as AuthenticatedDashboardDashboardIndexRouteImport } from './routes/_authenticated/_dashboard/dashboard/index'
import { Route as AdminDashboardAdminIndexRouteImport } from './routes/_admin/_dashboard/admin/index'
import { Route as AuthenticatedDashboardSettingsSecurityRouteImport } from './routes/_authenticated/_dashboard/settings/security'
import { Route as AuthenticatedDashboardSettingsProfileRouteImport } from './routes/_authenticated/_dashboard/settings/profile'
import { Route as AuthenticatedDashboardSettingsAuthMethodsRouteImport } from './routes/_authenticated/_dashboard/settings/auth-methods'
import { Route as AuthenticatedDashboardSettingsApiKeysRouteImport } from './routes/_authenticated/_dashboard/settings/api-keys'
import { Route as AuthenticatedDashboardOrgsNewRouteImport } from './routes/_authenticated/_dashboard/orgs/new'
import { Route as AuthenticatedDashboardOrgsSlugRouteImport } from './routes/_authenticated/_dashboard/orgs/$slug'
import { Route as AuthenticatedDashboardFeedRequestRouteImport } from './routes/_authenticated/_dashboard/feed/request'
import { Route as AdminDashboardAdminProjectsRouteImport } from './routes/_admin/_dashboard/admin/projects'
import { Route as AuthenticatedDashboardOrgsInvitesIdRouteImport } from './routes/_authenticated/_dashboard/orgs/invites.$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSkillRoute = PublicSkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHowToIntegrateRoute = PublicHowToIntegrateRouteImport.update({
  id: '/how-to-integrate',
  path: '/how-to-integrate',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAccountIdRoute = PublicAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const PublicFeedIndexRoute = PublicFeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAccountIdIndexRoute = PublicAccountIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicAccountIdRoute,
} as any)
const PublicFeedRoundIdRoute = PublicFeedRoundIdRouteImport.update({
  id: '/feed/$roundId',
  path: '/feed/$roundId',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrgsRoute =
  AuthenticatedDashboardOrgsRouteImport.update({
    id: '/orgs',
    path: '/orgs',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDashboardRoute =
  AuthenticatedDashboardDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AdminDashboardAdminRoute = AdminDashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AuthenticatedDashboardSettingsIndexRoute =
  AuthenticatedDashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardSettingsRoute,
  } as any)
const AuthenticatedDashboardOrgsIndexRoute =
  AuthenticatedDashboardOrgsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardOrgsRoute,
  } as any)
const AuthenticatedDashboardDashboardIndexRoute =
  AuthenticatedDashboardDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardDashboardRoute,
  } as any)
const AdminDashboardAdminIndexRoute =
  AdminDashboardAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardSettingsSecurityRoute =
  AuthenticatedDashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedDashboardSettingsRoute,
  } as any)
const AuthenticatedDashboardSettingsProfileRoute =
  AuthenticatedDashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardSettingsRoute,
  } as any)
const AuthenticatedDashboardSettingsAuthMethodsRoute =
  AuthenticatedDashboardSettingsAuthMethodsRouteImport.update({
    id: '/auth-methods',
    path: '/auth-methods',
    getParentRoute: () => AuthenticatedDashboardSettingsRoute,
  } as any)
const AuthenticatedDashboardSettingsApiKeysRoute =
  AuthenticatedDashboardSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedDashboardSettingsRoute,
  } as any)
const AuthenticatedDashboardOrgsNewRoute =
  AuthenticatedDashboardOrgsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardOrgsRoute,
  } as any)
const AuthenticatedDashboardOrgsSlugRoute =
  AuthenticatedDashboardOrgsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedDashboardOrgsRoute,
  } as any)
const AuthenticatedDashboardFeedRequestRoute =
  AuthenticatedDashboardFeedRequestRouteImport.update({
    id: '/feed/request',
    path: '/feed/request',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AdminDashboardAdminProjectsRoute =
  AdminDashboardAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AdminDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardOrgsInvitesIdRoute =
  AuthenticatedDashboardOrgsInvitesIdRouteImport.update({
    id: '/invites/$id',
    path: '/invites/$id',
    getParentRoute: () => AuthenticatedDashboardOrgsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/$accountId': typeof PublicAccountIdRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/how-to-integrate': typeof PublicHowToIntegrateRoute
  '/login': typeof PublicLoginRoute
  '/skill': typeof PublicSkillRoute
  '/admin': typeof AdminDashboardAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardDashboardRouteWithChildren
  '/orgs': typeof AuthenticatedDashboardOrgsRouteWithChildren
  '/settings': typeof AuthenticatedDashboardSettingsRouteWithChildren
  '/feed/$roundId': typeof PublicFeedRoundIdRoute
  '/$accountId/': typeof PublicAccountIdIndexRoute
  '/feed/': typeof PublicFeedIndexRoute
  '/admin/projects': typeof AdminDashboardAdminProjectsRoute
  '/feed/request': typeof AuthenticatedDashboardFeedRequestRoute
  '/orgs/$slug': typeof AuthenticatedDashboardOrgsSlugRoute
  '/orgs/new': typeof AuthenticatedDashboardOrgsNewRoute
  '/settings/api-keys': typeof AuthenticatedDashboardSettingsApiKeysRoute
  '/settings/auth-methods': typeof AuthenticatedDashboardSettingsAuthMethodsRoute
  '/settings/profile': typeof AuthenticatedDashboardSettingsProfileRoute
  '/settings/security': typeof AuthenticatedDashboardSettingsSecurityRoute
  '/admin/': typeof AdminDashboardAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardDashboardIndexRoute
  '/orgs/': typeof AuthenticatedDashboardOrgsIndexRoute
  '/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
  '/orgs/invites/$id': typeof AuthenticatedDashboardOrgsInvitesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/about': typeof PublicAboutRoute
  '/how-to-integrate': typeof PublicHowToIntegrateRoute
  '/login': typeof PublicLoginRoute
  '/skill': typeof PublicSkillRoute
  '/feed/$roundId': typeof PublicFeedRoundIdRoute
  '/$accountId': typeof PublicAccountIdIndexRoute
  '/feed': typeof PublicFeedIndexRoute
  '/admin/projects': typeof AdminDashboardAdminProjectsRoute
  '/feed/request': typeof AuthenticatedDashboardFeedRequestRoute
  '/orgs/$slug': typeof AuthenticatedDashboardOrgsSlugRoute
  '/orgs/new': typeof AuthenticatedDashboardOrgsNewRoute
  '/settings/api-keys': typeof AuthenticatedDashboardSettingsApiKeysRoute
  '/settings/auth-methods': typeof AuthenticatedDashboardSettingsAuthMethodsRoute
  '/settings/profile': typeof AuthenticatedDashboardSettingsProfileRoute
  '/settings/security': typeof AuthenticatedDashboardSettingsSecurityRoute
  '/admin': typeof AdminDashboardAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardDashboardIndexRoute
  '/orgs': typeof AuthenticatedDashboardOrgsIndexRoute
  '/settings': typeof AuthenticatedDashboardSettingsIndexRoute
  '/orgs/invites/$id': typeof AuthenticatedDashboardOrgsInvitesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_admin/_dashboard': typeof AdminDashboardRouteWithChildren
  '/_authenticated/_dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_public/$accountId': typeof PublicAccountIdRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/how-to-integrate': typeof PublicHowToIntegrateRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/skill': typeof PublicSkillRoute
  '/_public/': typeof PublicIndexRoute
  '/_admin/_dashboard/admin': typeof AdminDashboardAdminRouteWithChildren
  '/_authenticated/_dashboard/dashboard': typeof AuthenticatedDashboardDashboardRouteWithChildren
  '/_authenticated/_dashboard/orgs': typeof AuthenticatedDashboardOrgsRouteWithChildren
  '/_authenticated/_dashboard/settings': typeof AuthenticatedDashboardSettingsRouteWithChildren
  '/_public/feed/$roundId': typeof PublicFeedRoundIdRoute
  '/_public/$accountId/': typeof PublicAccountIdIndexRoute
  '/_public/feed/': typeof PublicFeedIndexRoute
  '/_admin/_dashboard/admin/projects': typeof AdminDashboardAdminProjectsRoute
  '/_authenticated/_dashboard/feed/request': typeof AuthenticatedDashboardFeedRequestRoute
  '/_authenticated/_dashboard/orgs/$slug': typeof AuthenticatedDashboardOrgsSlugRoute
  '/_authenticated/_dashboard/orgs/new': typeof AuthenticatedDashboardOrgsNewRoute
  '/_authenticated/_dashboard/settings/api-keys': typeof AuthenticatedDashboardSettingsApiKeysRoute
  '/_authenticated/_dashboard/settings/auth-methods': typeof AuthenticatedDashboardSettingsAuthMethodsRoute
  '/_authenticated/_dashboard/settings/profile': typeof AuthenticatedDashboardSettingsProfileRoute
  '/_authenticated/_dashboard/settings/security': typeof AuthenticatedDashboardSettingsSecurityRoute
  '/_admin/_dashboard/admin/': typeof AdminDashboardAdminIndexRoute
  '/_authenticated/_dashboard/dashboard/': typeof AuthenticatedDashboardDashboardIndexRoute
  '/_authenticated/_dashboard/orgs/': typeof AuthenticatedDashboardOrgsIndexRoute
  '/_authenticated/_dashboard/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
  '/_authenticated/_dashboard/orgs/invites/$id': typeof AuthenticatedDashboardOrgsInvitesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$accountId'
    | '/about'
    | '/how-to-integrate'
    | '/login'
    | '/skill'
    | '/admin'
    | '/dashboard'
    | '/orgs'
    | '/settings'
    | '/feed/$roundId'
    | '/$accountId/'
    | '/feed/'
    | '/admin/projects'
    | '/feed/request'
    | '/orgs/$slug'
    | '/orgs/new'
    | '/settings/api-keys'
    | '/settings/auth-methods'
    | '/settings/profile'
    | '/settings/security'
    | '/admin/'
    | '/dashboard/'
    | '/orgs/'
    | '/settings/'
    | '/orgs/invites/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/how-to-integrate'
    | '/login'
    | '/skill'
    | '/feed/$roundId'
    | '/$accountId'
    | '/feed'
    | '/admin/projects'
    | '/feed/request'
    | '/orgs/$slug'
    | '/orgs/new'
    | '/settings/api-keys'
    | '/settings/auth-methods'
    | '/settings/profile'
    | '/settings/security'
    | '/admin'
    | '/dashboard'
    | '/orgs'
    | '/settings'
    | '/orgs/invites/$id'
  id:
    | '__root__'
    | '/_admin'
    | '/_authenticated'
    | '/_public'
    | '/_admin/_dashboard'
    | '/_authenticated/_dashboard'
    | '/_public/$accountId'
    | '/_public/about'
    | '/_public/how-to-integrate'
    | '/_public/login'
    | '/_public/skill'
    | '/_public/'
    | '/_admin/_dashboard/admin'
    | '/_authenticated/_dashboard/dashboard'
    | '/_authenticated/_dashboard/orgs'
    | '/_authenticated/_dashboard/settings'
    | '/_public/feed/$roundId'
    | '/_public/$accountId/'
    | '/_public/feed/'
    | '/_admin/_dashboard/admin/projects'
    | '/_authenticated/_dashboard/feed/request'
    | '/_authenticated/_dashboard/orgs/$slug'
    | '/_authenticated/_dashboard/orgs/new'
    | '/_authenticated/_dashboard/settings/api-keys'
    | '/_authenticated/_dashboard/settings/auth-methods'
    | '/_authenticated/_dashboard/settings/profile'
    | '/_authenticated/_dashboard/settings/security'
    | '/_admin/_dashboard/admin/'
    | '/_authenticated/_dashboard/dashboard/'
    | '/_authenticated/_dashboard/orgs/'
    | '/_authenticated/_dashboard/settings/'
    | '/_authenticated/_dashboard/orgs/invites/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/skill': {
      id: '/_public/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof PublicSkillRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/how-to-integrate': {
      id: '/_public/how-to-integrate'
      path: '/how-to-integrate'
      fullPath: '/how-to-integrate'
      preLoaderRoute: typeof PublicHowToIntegrateRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/$accountId': {
      id: '/_public/$accountId'
      path: '/$accountId'
      fullPath: '/$accountId'
      preLoaderRoute: typeof PublicAccountIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/_dashboard': {
      id: '/_authenticated/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/_dashboard': {
      id: '/_admin/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/feed/': {
      id: '/_public/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof PublicFeedIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/$accountId/': {
      id: '/_public/$accountId/'
      path: '/'
      fullPath: '/$accountId/'
      preLoaderRoute: typeof PublicAccountIdIndexRouteImport
      parentRoute: typeof PublicAccountIdRoute
    }
    '/_public/feed/$roundId': {
      id: '/_public/feed/$roundId'
      path: '/feed/$roundId'
      fullPath: '/feed/$roundId'
      preLoaderRoute: typeof PublicFeedRoundIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/_dashboard/settings': {
      id: '/_authenticated/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/orgs': {
      id: '/_authenticated/_dashboard/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof AuthenticatedDashboardOrgsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/dashboard': {
      id: '/_authenticated/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_admin/_dashboard/admin': {
      id: '/_admin/_dashboard/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminDashboardAdminRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_authenticated/_dashboard/settings/': {
      id: '/_authenticated/_dashboard/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardSettingsRoute
    }
    '/_authenticated/_dashboard/orgs/': {
      id: '/_authenticated/_dashboard/orgs/'
      path: '/'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AuthenticatedDashboardOrgsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardOrgsRoute
    }
    '/_authenticated/_dashboard/dashboard/': {
      id: '/_authenticated/_dashboard/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardDashboardRoute
    }
    '/_admin/_dashboard/admin/': {
      id: '/_admin/_dashboard/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminDashboardAdminIndexRouteImport
      parentRoute: typeof AdminDashboardAdminRoute
    }
    '/_authenticated/_dashboard/settings/security': {
      id: '/_authenticated/_dashboard/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedDashboardSettingsRoute
    }
    '/_authenticated/_dashboard/settings/profile': {
      id: '/_authenticated/_dashboard/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardSettingsRoute
    }
    '/_authenticated/_dashboard/settings/auth-methods': {
      id: '/_authenticated/_dashboard/settings/auth-methods'
      path: '/auth-methods'
      fullPath: '/settings/auth-methods'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsAuthMethodsRouteImport
      parentRoute: typeof AuthenticatedDashboardSettingsRoute
    }
    '/_authenticated/_dashboard/settings/api-keys': {
      id: '/_authenticated/_dashboard/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedDashboardSettingsRoute
    }
    '/_authenticated/_dashboard/orgs/new': {
      id: '/_authenticated/_dashboard/orgs/new'
      path: '/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof AuthenticatedDashboardOrgsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardOrgsRoute
    }
    '/_authenticated/_dashboard/orgs/$slug': {
      id: '/_authenticated/_dashboard/orgs/$slug'
      path: '/$slug'
      fullPath: '/orgs/$slug'
      preLoaderRoute: typeof AuthenticatedDashboardOrgsSlugRouteImport
      parentRoute: typeof AuthenticatedDashboardOrgsRoute
    }
    '/_authenticated/_dashboard/feed/request': {
      id: '/_authenticated/_dashboard/feed/request'
      path: '/feed/request'
      fullPath: '/feed/request'
      preLoaderRoute: typeof AuthenticatedDashboardFeedRequestRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_admin/_dashboard/admin/projects': {
      id: '/_admin/_dashboard/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminDashboardAdminProjectsRouteImport
      parentRoute: typeof AdminDashboardAdminRoute
    }
    '/_authenticated/_dashboard/orgs/invites/$id': {
      id: '/_authenticated/_dashboard/orgs/invites/$id'
      path: '/invites/$id'
      fullPath: '/orgs/invites/$id'
      preLoaderRoute: typeof AuthenticatedDashboardOrgsInvitesIdRouteImport
      parentRoute: typeof AuthenticatedDashboardOrgsRoute
    }
  }
}

interface AdminDashboardAdminRouteChildren {
  AdminDashboardAdminProjectsRoute: typeof AdminDashboardAdminProjectsRoute
  AdminDashboardAdminIndexRoute: typeof AdminDashboardAdminIndexRoute
}

const AdminDashboardAdminRouteChildren: AdminDashboardAdminRouteChildren = {
  AdminDashboardAdminProjectsRoute: AdminDashboardAdminProjectsRoute,
  AdminDashboardAdminIndexRoute: AdminDashboardAdminIndexRoute,
}

const AdminDashboardAdminRouteWithChildren =
  AdminDashboardAdminRoute._addFileChildren(AdminDashboardAdminRouteChildren)

interface AdminDashboardRouteChildren {
  AdminDashboardAdminRoute: typeof AdminDashboardAdminRouteWithChildren
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardAdminRoute: AdminDashboardAdminRouteWithChildren,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedDashboardDashboardRouteChildren {
  AuthenticatedDashboardDashboardIndexRoute: typeof AuthenticatedDashboardDashboardIndexRoute
}

const AuthenticatedDashboardDashboardRouteChildren: AuthenticatedDashboardDashboardRouteChildren =
  {
    AuthenticatedDashboardDashboardIndexRoute:
      AuthenticatedDashboardDashboardIndexRoute,
  }

const AuthenticatedDashboardDashboardRouteWithChildren =
  AuthenticatedDashboardDashboardRoute._addFileChildren(
    AuthenticatedDashboardDashboardRouteChildren,
  )

interface AuthenticatedDashboardOrgsRouteChildren {
  AuthenticatedDashboardOrgsSlugRoute: typeof AuthenticatedDashboardOrgsSlugRoute
  AuthenticatedDashboardOrgsNewRoute: typeof AuthenticatedDashboardOrgsNewRoute
  AuthenticatedDashboardOrgsIndexRoute: typeof AuthenticatedDashboardOrgsIndexRoute
  AuthenticatedDashboardOrgsInvitesIdRoute: typeof AuthenticatedDashboardOrgsInvitesIdRoute
}

const AuthenticatedDashboardOrgsRouteChildren: AuthenticatedDashboardOrgsRouteChildren =
  {
    AuthenticatedDashboardOrgsSlugRoute: AuthenticatedDashboardOrgsSlugRoute,
    AuthenticatedDashboardOrgsNewRoute: AuthenticatedDashboardOrgsNewRoute,
    AuthenticatedDashboardOrgsIndexRoute: AuthenticatedDashboardOrgsIndexRoute,
    AuthenticatedDashboardOrgsInvitesIdRoute:
      AuthenticatedDashboardOrgsInvitesIdRoute,
  }

const AuthenticatedDashboardOrgsRouteWithChildren =
  AuthenticatedDashboardOrgsRoute._addFileChildren(
    AuthenticatedDashboardOrgsRouteChildren,
  )

interface AuthenticatedDashboardSettingsRouteChildren {
  AuthenticatedDashboardSettingsApiKeysRoute: typeof AuthenticatedDashboardSettingsApiKeysRoute
  AuthenticatedDashboardSettingsAuthMethodsRoute: typeof AuthenticatedDashboardSettingsAuthMethodsRoute
  AuthenticatedDashboardSettingsProfileRoute: typeof AuthenticatedDashboardSettingsProfileRoute
  AuthenticatedDashboardSettingsSecurityRoute: typeof AuthenticatedDashboardSettingsSecurityRoute
  AuthenticatedDashboardSettingsIndexRoute: typeof AuthenticatedDashboardSettingsIndexRoute
}

const AuthenticatedDashboardSettingsRouteChildren: AuthenticatedDashboardSettingsRouteChildren =
  {
    AuthenticatedDashboardSettingsApiKeysRoute:
      AuthenticatedDashboardSettingsApiKeysRoute,
    AuthenticatedDashboardSettingsAuthMethodsRoute:
      AuthenticatedDashboardSettingsAuthMethodsRoute,
    AuthenticatedDashboardSettingsProfileRoute:
      AuthenticatedDashboardSettingsProfileRoute,
    AuthenticatedDashboardSettingsSecurityRoute:
      AuthenticatedDashboardSettingsSecurityRoute,
    AuthenticatedDashboardSettingsIndexRoute:
      AuthenticatedDashboardSettingsIndexRoute,
  }

const AuthenticatedDashboardSettingsRouteWithChildren =
  AuthenticatedDashboardSettingsRoute._addFileChildren(
    AuthenticatedDashboardSettingsRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardDashboardRoute: typeof AuthenticatedDashboardDashboardRouteWithChildren
  AuthenticatedDashboardOrgsRoute: typeof AuthenticatedDashboardOrgsRouteWithChildren
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRouteWithChildren
  AuthenticatedDashboardFeedRequestRoute: typeof AuthenticatedDashboardFeedRequestRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardDashboardRoute:
      AuthenticatedDashboardDashboardRouteWithChildren,
    AuthenticatedDashboardOrgsRoute:
      AuthenticatedDashboardOrgsRouteWithChildren,
    AuthenticatedDashboardSettingsRoute:
      AuthenticatedDashboardSettingsRouteWithChildren,
    AuthenticatedDashboardFeedRequestRoute:
      AuthenticatedDashboardFeedRequestRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicAccountIdRouteChildren {
  PublicAccountIdIndexRoute: typeof PublicAccountIdIndexRoute
}

const PublicAccountIdRouteChildren: PublicAccountIdRouteChildren = {
  PublicAccountIdIndexRoute: PublicAccountIdIndexRoute,
}

const PublicAccountIdRouteWithChildren = PublicAccountIdRoute._addFileChildren(
  PublicAccountIdRouteChildren,
)

interface PublicRouteChildren {
  PublicAccountIdRoute: typeof PublicAccountIdRouteWithChildren
  PublicAboutRoute: typeof PublicAboutRoute
  PublicHowToIntegrateRoute: typeof PublicHowToIntegrateRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSkillRoute: typeof PublicSkillRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicFeedRoundIdRoute: typeof PublicFeedRoundIdRoute
  PublicFeedIndexRoute: typeof PublicFeedIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAccountIdRoute: PublicAccountIdRouteWithChildren,
  PublicAboutRoute: PublicAboutRoute,
  PublicHowToIntegrateRoute: PublicHowToIntegrateRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicSkillRoute: PublicSkillRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicFeedRoundIdRoute: PublicFeedRoundIdRoute,
  PublicFeedIndexRoute: PublicFeedIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
