/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSkillRouteImport } from './routes/_layout/skill'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutFeedbackRoundIdRouteImport } from './routes/_layout/feedback/$roundId'
import { Route as LayoutAuthenticatedSettingsRouteImport } from './routes/_layout/_authenticated/settings'
import { Route as LayoutAuthenticatedHomeRouteImport } from './routes/_layout/_authenticated/home'
import { Route as LayoutAuthenticatedAdminRouteImport } from './routes/_layout/_authenticated/admin'
import { Route as LayoutAuthenticatedTenantIndexRouteImport } from './routes/_layout/_authenticated/tenant/index'
import { Route as LayoutAuthenticatedSettingsIndexRouteImport } from './routes/_layout/_authenticated/settings/index'
import { Route as LayoutAuthenticatedOrganizationsIndexRouteImport } from './routes/_layout/_authenticated/organizations/index'
import { Route as LayoutAuthenticatedTenantNewRouteImport } from './routes/_layout/_authenticated/tenant/new'
import { Route as LayoutAuthenticatedTenantTenantIdRouteImport } from './routes/_layout/_authenticated/tenant/$tenantId'
import { Route as LayoutAuthenticatedSettingsSecurityRouteImport } from './routes/_layout/_authenticated/settings/security'
import { Route as LayoutAuthenticatedSettingsProfileRouteImport } from './routes/_layout/_authenticated/settings/profile'
import { Route as LayoutAuthenticatedSettingsAuthMethodsRouteImport } from './routes/_layout/_authenticated/settings/auth-methods'
import { Route as LayoutAuthenticatedOrganizationsNewRouteImport } from './routes/_layout/_authenticated/organizations/new'
import { Route as LayoutAuthenticatedOrganizationsSlugRouteImport } from './routes/_layout/_authenticated/organizations/$slug'
import { Route as LayoutAuthenticatedFeedbackRequestRouteImport } from './routes/_layout/_authenticated/feedback/request'
import { Route as LayoutAuthenticatedAcceptInvitationIdRouteImport } from './routes/_layout/_authenticated/accept-invitation.$id'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSkillRoute = LayoutSkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFeedbackRoundIdRoute = LayoutFeedbackRoundIdRouteImport.update({
  id: '/feedback/$roundId',
  path: '/feedback/$roundId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedSettingsRoute =
  LayoutAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedHomeRoute = LayoutAuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutAuthenticatedRoute,
} as any)
const LayoutAuthenticatedAdminRoute =
  LayoutAuthenticatedAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedTenantIndexRoute =
  LayoutAuthenticatedTenantIndexRouteImport.update({
    id: '/tenant/',
    path: '/tenant/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedSettingsIndexRoute =
  LayoutAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedOrganizationsIndexRoute =
  LayoutAuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedTenantNewRoute =
  LayoutAuthenticatedTenantNewRouteImport.update({
    id: '/tenant/new',
    path: '/tenant/new',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedTenantTenantIdRoute =
  LayoutAuthenticatedTenantTenantIdRouteImport.update({
    id: '/tenant/$tenantId',
    path: '/tenant/$tenantId',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedSettingsSecurityRoute =
  LayoutAuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedSettingsProfileRoute =
  LayoutAuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedSettingsAuthMethodsRoute =
  LayoutAuthenticatedSettingsAuthMethodsRouteImport.update({
    id: '/auth-methods',
    path: '/auth-methods',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedOrganizationsNewRoute =
  LayoutAuthenticatedOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedOrganizationsSlugRoute =
  LayoutAuthenticatedOrganizationsSlugRouteImport.update({
    id: '/organizations/$slug',
    path: '/organizations/$slug',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedFeedbackRequestRoute =
  LayoutAuthenticatedFeedbackRequestRouteImport.update({
    id: '/feedback/request',
    path: '/feedback/request',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedAcceptInvitationIdRoute =
  LayoutAuthenticatedAcceptInvitationIdRouteImport.update({
    id: '/accept-invitation/$id',
    path: '/accept-invitation/$id',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/login': typeof LayoutLoginRoute
  '/skill': typeof LayoutSkillRoute
  '/admin': typeof LayoutAuthenticatedAdminRoute
  '/home': typeof LayoutAuthenticatedHomeRoute
  '/settings': typeof LayoutAuthenticatedSettingsRouteWithChildren
  '/feedback/$roundId': typeof LayoutFeedbackRoundIdRoute
  '/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/feedback/request': typeof LayoutAuthenticatedFeedbackRequestRoute
  '/organizations/$slug': typeof LayoutAuthenticatedOrganizationsSlugRoute
  '/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/settings/auth-methods': typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  '/settings/profile': typeof LayoutAuthenticatedSettingsProfileRoute
  '/settings/security': typeof LayoutAuthenticatedSettingsSecurityRoute
  '/tenant/$tenantId': typeof LayoutAuthenticatedTenantTenantIdRoute
  '/tenant/new': typeof LayoutAuthenticatedTenantNewRoute
  '/organizations/': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/settings/': typeof LayoutAuthenticatedSettingsIndexRoute
  '/tenant/': typeof LayoutAuthenticatedTenantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/login': typeof LayoutLoginRoute
  '/skill': typeof LayoutSkillRoute
  '/admin': typeof LayoutAuthenticatedAdminRoute
  '/home': typeof LayoutAuthenticatedHomeRoute
  '/feedback/$roundId': typeof LayoutFeedbackRoundIdRoute
  '/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/feedback/request': typeof LayoutAuthenticatedFeedbackRequestRoute
  '/organizations/$slug': typeof LayoutAuthenticatedOrganizationsSlugRoute
  '/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/settings/auth-methods': typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  '/settings/profile': typeof LayoutAuthenticatedSettingsProfileRoute
  '/settings/security': typeof LayoutAuthenticatedSettingsSecurityRoute
  '/tenant/$tenantId': typeof LayoutAuthenticatedTenantTenantIdRoute
  '/tenant/new': typeof LayoutAuthenticatedTenantNewRoute
  '/organizations': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/settings': typeof LayoutAuthenticatedSettingsIndexRoute
  '/tenant': typeof LayoutAuthenticatedTenantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/skill': typeof LayoutSkillRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_authenticated/admin': typeof LayoutAuthenticatedAdminRoute
  '/_layout/_authenticated/home': typeof LayoutAuthenticatedHomeRoute
  '/_layout/_authenticated/settings': typeof LayoutAuthenticatedSettingsRouteWithChildren
  '/_layout/feedback/$roundId': typeof LayoutFeedbackRoundIdRoute
  '/_layout/_authenticated/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/_layout/_authenticated/feedback/request': typeof LayoutAuthenticatedFeedbackRequestRoute
  '/_layout/_authenticated/organizations/$slug': typeof LayoutAuthenticatedOrganizationsSlugRoute
  '/_layout/_authenticated/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/_layout/_authenticated/settings/auth-methods': typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  '/_layout/_authenticated/settings/profile': typeof LayoutAuthenticatedSettingsProfileRoute
  '/_layout/_authenticated/settings/security': typeof LayoutAuthenticatedSettingsSecurityRoute
  '/_layout/_authenticated/tenant/$tenantId': typeof LayoutAuthenticatedTenantTenantIdRoute
  '/_layout/_authenticated/tenant/new': typeof LayoutAuthenticatedTenantNewRoute
  '/_layout/_authenticated/organizations/': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/_layout/_authenticated/settings/': typeof LayoutAuthenticatedSettingsIndexRoute
  '/_layout/_authenticated/tenant/': typeof LayoutAuthenticatedTenantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/skill'
    | '/admin'
    | '/home'
    | '/settings'
    | '/feedback/$roundId'
    | '/accept-invitation/$id'
    | '/feedback/request'
    | '/organizations/$slug'
    | '/organizations/new'
    | '/settings/auth-methods'
    | '/settings/profile'
    | '/settings/security'
    | '/tenant/$tenantId'
    | '/tenant/new'
    | '/organizations/'
    | '/settings/'
    | '/tenant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/skill'
    | '/admin'
    | '/home'
    | '/feedback/$roundId'
    | '/accept-invitation/$id'
    | '/feedback/request'
    | '/organizations/$slug'
    | '/organizations/new'
    | '/settings/auth-methods'
    | '/settings/profile'
    | '/settings/security'
    | '/tenant/$tenantId'
    | '/tenant/new'
    | '/organizations'
    | '/settings'
    | '/tenant'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_authenticated'
    | '/_layout/about'
    | '/_layout/login'
    | '/_layout/skill'
    | '/_layout/'
    | '/_layout/_authenticated/admin'
    | '/_layout/_authenticated/home'
    | '/_layout/_authenticated/settings'
    | '/_layout/feedback/$roundId'
    | '/_layout/_authenticated/accept-invitation/$id'
    | '/_layout/_authenticated/feedback/request'
    | '/_layout/_authenticated/organizations/$slug'
    | '/_layout/_authenticated/organizations/new'
    | '/_layout/_authenticated/settings/auth-methods'
    | '/_layout/_authenticated/settings/profile'
    | '/_layout/_authenticated/settings/security'
    | '/_layout/_authenticated/tenant/$tenantId'
    | '/_layout/_authenticated/tenant/new'
    | '/_layout/_authenticated/organizations/'
    | '/_layout/_authenticated/settings/'
    | '/_layout/_authenticated/tenant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/skill': {
      id: '/_layout/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof LayoutSkillRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/feedback/$roundId': {
      id: '/_layout/feedback/$roundId'
      path: '/feedback/$roundId'
      fullPath: '/feedback/$roundId'
      preLoaderRoute: typeof LayoutFeedbackRoundIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/settings': {
      id: '/_layout/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/home': {
      id: '/_layout/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutAuthenticatedHomeRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/admin': {
      id: '/_layout/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAuthenticatedAdminRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/tenant/': {
      id: '/_layout/_authenticated/tenant/'
      path: '/tenant'
      fullPath: '/tenant/'
      preLoaderRoute: typeof LayoutAuthenticatedTenantIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/settings/': {
      id: '/_layout/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/organizations/': {
      id: '/_layout/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/tenant/new': {
      id: '/_layout/_authenticated/tenant/new'
      path: '/tenant/new'
      fullPath: '/tenant/new'
      preLoaderRoute: typeof LayoutAuthenticatedTenantNewRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/tenant/$tenantId': {
      id: '/_layout/_authenticated/tenant/$tenantId'
      path: '/tenant/$tenantId'
      fullPath: '/tenant/$tenantId'
      preLoaderRoute: typeof LayoutAuthenticatedTenantTenantIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/settings/security': {
      id: '/_layout/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/settings/profile': {
      id: '/_layout/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsProfileRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/settings/auth-methods': {
      id: '/_layout/_authenticated/settings/auth-methods'
      path: '/auth-methods'
      fullPath: '/settings/auth-methods'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsAuthMethodsRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/organizations/new': {
      id: '/_layout/_authenticated/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsNewRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/organizations/$slug': {
      id: '/_layout/_authenticated/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsSlugRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/feedback/request': {
      id: '/_layout/_authenticated/feedback/request'
      path: '/feedback/request'
      fullPath: '/feedback/request'
      preLoaderRoute: typeof LayoutAuthenticatedFeedbackRequestRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/accept-invitation/$id': {
      id: '/_layout/_authenticated/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof LayoutAuthenticatedAcceptInvitationIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
  }
}

interface LayoutAuthenticatedSettingsRouteChildren {
  LayoutAuthenticatedSettingsAuthMethodsRoute: typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  LayoutAuthenticatedSettingsProfileRoute: typeof LayoutAuthenticatedSettingsProfileRoute
  LayoutAuthenticatedSettingsSecurityRoute: typeof LayoutAuthenticatedSettingsSecurityRoute
  LayoutAuthenticatedSettingsIndexRoute: typeof LayoutAuthenticatedSettingsIndexRoute
}

const LayoutAuthenticatedSettingsRouteChildren: LayoutAuthenticatedSettingsRouteChildren =
  {
    LayoutAuthenticatedSettingsAuthMethodsRoute:
      LayoutAuthenticatedSettingsAuthMethodsRoute,
    LayoutAuthenticatedSettingsProfileRoute:
      LayoutAuthenticatedSettingsProfileRoute,
    LayoutAuthenticatedSettingsSecurityRoute:
      LayoutAuthenticatedSettingsSecurityRoute,
    LayoutAuthenticatedSettingsIndexRoute:
      LayoutAuthenticatedSettingsIndexRoute,
  }

const LayoutAuthenticatedSettingsRouteWithChildren =
  LayoutAuthenticatedSettingsRoute._addFileChildren(
    LayoutAuthenticatedSettingsRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedAdminRoute: typeof LayoutAuthenticatedAdminRoute
  LayoutAuthenticatedHomeRoute: typeof LayoutAuthenticatedHomeRoute
  LayoutAuthenticatedSettingsRoute: typeof LayoutAuthenticatedSettingsRouteWithChildren
  LayoutAuthenticatedAcceptInvitationIdRoute: typeof LayoutAuthenticatedAcceptInvitationIdRoute
  LayoutAuthenticatedFeedbackRequestRoute: typeof LayoutAuthenticatedFeedbackRequestRoute
  LayoutAuthenticatedOrganizationsSlugRoute: typeof LayoutAuthenticatedOrganizationsSlugRoute
  LayoutAuthenticatedOrganizationsNewRoute: typeof LayoutAuthenticatedOrganizationsNewRoute
  LayoutAuthenticatedTenantTenantIdRoute: typeof LayoutAuthenticatedTenantTenantIdRoute
  LayoutAuthenticatedTenantNewRoute: typeof LayoutAuthenticatedTenantNewRoute
  LayoutAuthenticatedOrganizationsIndexRoute: typeof LayoutAuthenticatedOrganizationsIndexRoute
  LayoutAuthenticatedTenantIndexRoute: typeof LayoutAuthenticatedTenantIndexRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedAdminRoute: LayoutAuthenticatedAdminRoute,
  LayoutAuthenticatedHomeRoute: LayoutAuthenticatedHomeRoute,
  LayoutAuthenticatedSettingsRoute:
    LayoutAuthenticatedSettingsRouteWithChildren,
  LayoutAuthenticatedAcceptInvitationIdRoute:
    LayoutAuthenticatedAcceptInvitationIdRoute,
  LayoutAuthenticatedFeedbackRequestRoute:
    LayoutAuthenticatedFeedbackRequestRoute,
  LayoutAuthenticatedOrganizationsSlugRoute:
    LayoutAuthenticatedOrganizationsSlugRoute,
  LayoutAuthenticatedOrganizationsNewRoute:
    LayoutAuthenticatedOrganizationsNewRoute,
  LayoutAuthenticatedTenantTenantIdRoute:
    LayoutAuthenticatedTenantTenantIdRoute,
  LayoutAuthenticatedTenantNewRoute: LayoutAuthenticatedTenantNewRoute,
  LayoutAuthenticatedOrganizationsIndexRoute:
    LayoutAuthenticatedOrganizationsIndexRoute,
  LayoutAuthenticatedTenantIndexRoute: LayoutAuthenticatedTenantIndexRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutSkillRoute: typeof LayoutSkillRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutFeedbackRoundIdRoute: typeof LayoutFeedbackRoundIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutSkillRoute: LayoutSkillRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutFeedbackRoundIdRoute: LayoutFeedbackRoundIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
